#!/usr/bin/perl -w
use strict;

# code mostly generated by the OVH interface at
# http://www.ovh.com/soapi/de/

# read config

my ($user, $pass, $host, $mail);
open CONFIG, '<', "$ENV{HOME}/.ovh" or die "can't open `~/.ovh': $!\n";
while (my $line = <CONFIG>) {
    chomp $line;
    $line =~ tr/ //d;
    if ($line =~ /^(.+)=(.+)$/) {
	my ($key, $val) = ($1, $2);
	if ($key eq 'user') {
	    $user = $val;
	} elsif ($key eq 'pass') {
	    $pass = $val;
	} elsif ($key eq 'host') {
	    $host = $val;
#	} elsif ($key eq 'mail') {
#	    $mail = $val;
	}	    
    }
}
close CONFIG or die "can't close `~/.ovh': $!\n";
die "no user in config\n"     unless defined $user;
die "no password in config\n" unless defined $pass;
die "no hostname in config\n" unless defined $host;
#die "no email in config\n"    unless defined $mail;

# do connection

use Data::Dumper;
use SOAP::Lite
 on_fault => sub { my($soap, $res) = @_; die ref $res ? $res->faultstring : $soap->transport->status; };

my $soap = SOAP::Lite
 -> uri('https://soapi.ovh.com/manager')
 -> proxy('https://www.ovh.com:1664');

#login
my $result = $soap->call( 'login' => ($user, $pass, 'de', 0) );
print "login successfull\n";
my $session = $result->result();

#dedicatedHardRebootDo
$soap->call( 'dedicatedHardRebootDo' => ($session, $host, 'hat sich aufgehaengt') );
print "dedicatedHardRebootDo successful\n";

#logout
$soap->call( 'logout' => ( $session ) );
print "logout successful\n";
